name: project_h
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  hive: ^2.0.3
  hive_flutter: ^1.0.0
  # format dates
  intl: ^0.17.0
  http: ^0.13.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


